services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
    container_name: salescraft
    restart: unless-stopped
    ports:
      - "3004:3004"
    env_file: .env
    networks:
      - shared_net

networks:
  shared_net:
    external: true
    name: shared_net
